### ISSUE TITLE
Cannot use with the new two-step

### ISSUE THREAD

**Issue by efewqefwfd** [theusaf/kahoot.js-updated#7]
I cannot use this with the new two-step security. Maybe make it so you can enter the pattern or it guesses?

**Comment by theusaf** [comment]
I am unable to reproduce this issue. 2-Step security doesn't appear to have changed. You can answer the two-step security by doing something like this:
`session.on("2Step",()=>{session.answer2Step([0,1,2,3])});`
You can brute force this using loops as well.

Please reply if this issue is not solved still.

**Comment by theusaf** [comment]
Closing due to assumption that there is no issue anymore.
